baseURL = "https://www.lonewolflabs.co"
languageCode = "en-us"
title = "Lone Wolf Labs"
themesDir = "themes"
theme = "hugo-serif-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"
    
[params]
  # In most cases you will only want to use either one of these. If you have Google Analytics included in your GTM tags don't put your GA ID here. Otherwise your data might be useless.
  google_analytics_id = ""
  google_tag_manager_id = ""

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = false  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo.png"
    mobile_height = "36px"
    desktop = "images/logo/logo.png"
    desktop_height = "36px"
    alt = "Lone Wolf Labs"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'Copyright 2021 Lone Wolf Labs, LLC - All Rights Reserved'

